### Listar todas as tarefas
GET http://localhost:5000/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}

### Alterar status da tarefa pelo id
PUT http://localhost:5000/tarefas/alterar/0acb4b91-8eb0-41c0-afe7-d20a3359af4a
Content-Type: application/json

### Listagem das tarefas não concluidas
GET http://localhost:5000/tarefas/naoconcluidas

### Listagem das tarefas concluidas
GET http://localhost:5000/tarefas/concluidas

